### ISSUE TITLE
Where are the builds?

### ISSUE THREAD

**Issue by AnErrupTion** [napalmtorch/AerOS#5]
In the readme there's a little image with build passing as text, but when clicking it redirects to the project's page. Also there's no actions set up so I guess it's not there. So where are they? Do they even exist?

**Comment by KM198912** [comment]
Currently we dont provide public builds but the setup should be pretty easy to run on itself if you have a cross compiler setup

**Comment by KM198912** [comment]
you can give this a try http://144.76.18.59:8080/job/AerOS/lastSuccessfulBuild/artifact/AerOS.iso it should allow you to download
